// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranTrungVietHoang_2280601072_Test.Models;

#nullable disable

namespace TranTrungVietHoang_2280601072_Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.ChiTietDangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .HasColumnType("int");

                    b.Property<string>("MaHP")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDK", "MaHP");

                    b.HasIndex("MaHP");

                    b.ToTable("ChiTietDangKy");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDK"));

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDK");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongDuKien")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHP");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNganh");

                    b.ToTable("NganhHoc");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSV");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.ChiTietDangKy", b =>
                {
                    b.HasOne("TranTrungVietHoang_2280601072_Test.Models.DangKy", "DangKy")
                        .WithMany("ChiTietDangKys")
                        .HasForeignKey("MaDK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TranTrungVietHoang_2280601072_Test.Models.HocPhan", "HocPhan")
                        .WithMany("ChiTietDangKys")
                        .HasForeignKey("MaHP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.DangKy", b =>
                {
                    b.HasOne("TranTrungVietHoang_2280601072_Test.Models.SinhVien", "SinhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.SinhVien", b =>
                {
                    b.HasOne("TranTrungVietHoang_2280601072_Test.Models.NganhHoc", "NganhHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.DangKy", b =>
                {
                    b.Navigation("ChiTietDangKys");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.HocPhan", b =>
                {
                    b.Navigation("ChiTietDangKys");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("TranTrungVietHoang_2280601072_Test.Models.SinhVien", b =>
                {
                    b.Navigation("DangKys");
                });
#pragma warning restore 612, 618
        }
    }
}
